# Generated by Django 2.2.8 on 2020-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
