# Generated by Django 2.2.7 on 2020-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20200204_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
