# Generated by Django 2.2.6 on 2020-02-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_district_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
