# Generated by Django 2.2.8 on 2020-02-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0007_seller_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='Name',
        ),
    ]
