# Generated by Django 2.2.8 on 2020-02-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_auto_20200206_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='Dob',
        ),
    ]
