# Generated by Django 2.2.6 on 2020-02-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_auto_20200206_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropstats',
            name='Fe',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='cropstats',
            name='K',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='cropstats',
            name='N',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='cropstats',
            name='OC',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='cropstats',
            name='P',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='cropstats',
            name='ph',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
