# Generated by Django 2.2.8 on 2020-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_remove_farmer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
