# Generated by Django 2.2.6 on 2020-02-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_auto_20200206_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
