# Generated by Django 2.2.6 on 2020-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0012_auto_20200206_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
