# Generated by Django 2.2.8 on 2020-02-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_bankexecutive_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='rainfall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
