# Generated by Django 3.0.1 on 2020-03-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0013_auto_20200206_2256'),
        ('farmers', '0014_district_rainfall'),
    ]

    operations = [
    ]
