# Generated by Django 2.2.6 on 2020-02-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0006_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.TextField()),
                ('Requirement_Desc', models.TextField()),
                ('Lock', models.IntegerField()),
                ('Delivery', models.DateField()),
                ('Publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.Dealer')),
            ],
        ),
    ]
